name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on an Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out your repository code
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set the Node.js version you are using

      - name: Install dependencies
        run: |
          cd backend  # Navigate to the 'backend' directory
          npm install  # Install the dependencies from package.json in the backend

      - name: Build project
        run: |
          cd backend  # Ensure you're in the backend directory
          npm run build  # Build your project (if you need to run a build step)

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job runs before deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Check out your repository code

      - name: Set up Azure CLI
        uses: azure/cli-action@v2  # Corrected to v2 for Azure CLI setup
        
      - name: Azure WebApp Deploy
        uses: azure/webapps-deploy@v2  # Use the Azure Web Apps deploy action
        with:
          app-name: 'cloud-devops-app'  # Replace with your Azure Web App name
          slot-name: 'production'  # Replace if you want to use a different slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Secret containing the publish profile
          package: ./backend  # Path to your app package, specify the backend folder
